import { useEffect, useRef } from 'react'
import CytoscapeComponent from 'react-cytoscapejs'
import cytoscape, { type Core } from 'cytoscape'
import { Maximize2, Minus, Plus, RotateCcw } from 'lucide-react'
import type { GraphEdge, GraphNode } from '../types/graph'
import { roleMeta } from '../data/mockData'

interface NetworkGraphProps { nodes: GraphNode[]; edges: GraphEdge[]; selectedId: string; onSelect: (id: string) => void; query: string }

export function NetworkGraph({ nodes, edges, selectedId, onSelect, query }: NetworkGraphProps) {
  const cyRef = useRef<Core | null>(null)
  useEffect(() => { if (query && cyRef.current) { const found = nodes.find((node) => node.gid.toLowerCase() === query.trim().toLowerCase()); if (found) { cyRef.current.$(`#${found.id}`).select(); cyRef.current.animate({ center: { eles: cyRef.current.$(`#${found.id}`) }, zoom: 1.5 }, { duration: 450 }) } } }, [query, nodes])
  const elements = [...nodes.map((node) => ({ data: { id: node.id, label: node.gid, role: node.role, color: roleMeta[node.role].color, selected: node.id === selectedId }, position: { x: node.x * 7.8, y: node.y * 5.4 } })), ...edges.map((edge) => ({ data: { id: edge.id, source: edge.source, target: edge.target, amount: edge.amount } }))]
  return <section className="graph-panel"><div className="graph-topbar"><div><p className="eyebrow">LIVE NETWORK VIEW</p><h2>Transaction topology <span className="live-dot" /> <span className="live-label">LIVE</span></h2></div><div className="graph-actions"><button className="icon-button" onClick={() => cyRef.current?.fit(undefined, 35)} aria-label="Fit graph"><Maximize2 size={16} /></button><button className="icon-button" onClick={() => cyRef.current?.zoom((cyRef.current?.zoom() ?? 1) + 0.2)} aria-label="Zoom in"><Plus size={16} /></button><button className="icon-button" onClick={() => cyRef.current?.zoom(Math.max(.4, (cyRef.current?.zoom() ?? 1) - 0.2))} aria-label="Zoom out"><Minus size={16} /></button><button className="icon-button" onClick={() => cyRef.current?.reset()} aria-label="Reset view"><RotateCcw size={15} /></button></div></div><div className="graph-stage"><CytoscapeComponent cy={(cy: Core) => { cyRef.current = cy; cy.on('tap', 'node', (event: any) => onSelect(event.target.id())) }} elements={elements} stylesheet={[{ selector: 'node', style: { 'background-color': 'data(color)', label: 'data(label)', color: '#f4f4f5', 'font-size': 10, 'font-family': 'Inter, sans-serif', 'text-valign': 'bottom', 'text-margin-y': 8, width: 20, height: 20, 'border-width': 2, 'border-color': '#11141b' } }, { selector: 'node:selected', style: { 'border-width': 4, 'border-color': '#f4f4f5', width: 28, height: 28, 'font-size': 12, 'font-weight': 700 } }, { selector: 'edge', style: { width: 1.4, 'line-color': '#3a414e', 'target-arrow-color': '#657080', 'target-arrow-shape': 'triangle', 'curve-style': 'bezier', opacity: 0.8, label: 'data(amount)', color: '#778191', 'font-size': 8, 'text-background-color': '#0d1016', 'text-background-opacity': 0.8, 'text-background-padding': 3 } }]} layout={{ name: 'preset', fit: true, padding: 55 }} style={{ width: '100%', height: '100%' }} /></div><div className="graph-footer"><span><i className="edge-swatch" /> payer → receiver</span><span><i className="node-swatch" /> click a node to inspect</span><span className="graph-hint">Scroll to zoom · drag to pan</span></div></section>
}
