import { ArrowDownLeft, ArrowUpRight, CircleHelp, Network, ShieldAlert } from 'lucide-react'
import type { ReactNode } from 'react'
import type { GraphNode } from '../types/graph'
import { clusterMeta, formatScore, getSignalMeta, roleMeta } from '../data/mockData'
import { EntitySignalIcon, SignalBadge } from './EntitySignalIcon'

export function NodeDetails({ node }: { node: GraphNode }) {
  const role = roleMeta[node.role]
  const signal = getSignalMeta(node.priorityScore)
  const cluster = clusterMeta[node.clusterId]
  return <aside className="details-panel"><div className="details-header"><div><p className="eyebrow">ВЫБРАННЫЙ УЗЕЛ</p><h2>Карточка клиента</h2></div><span className="status-pill"><span /> Сеть активна</span></div><div className="entity-card"><div className="entity-top"><EntitySignalIcon priorityScore={node.priorityScore} size={48} animate /><div><span className="entity-gid">GID {node.gid}</span><span className="entity-role" style={{ color: role.color }}><Network size={12} />{role.label}</span></div><div className="cluster-pill">Кластер #{node.clusterId}</div></div><div className="signal-summary"><span className="signal-summary__label">Аналитический сигнал</span><SignalBadge priorityScore={node.priorityScore} /><span className="signal-summary__help" style={{ color: signal.color }}>Приоритет проверки</span></div><div className="score-row"><div><span>Уверенность роли</span><strong>{formatScore(node.roleScore)}</strong></div><div><span>Приоритет</span><strong style={{ color: signal.color }}>{formatScore(node.priorityScore)}</strong></div></div></div><div className="metrics-grid"><Metric icon={<ArrowDownLeft size={15} />} label="Входящих связей" value={node.incoming.toString()} /><Metric icon={<ArrowUpRight size={15} />} label="Исходящих связей" value={node.outgoing.toString()} /><Metric label="Получено" value={node.received} /><Metric label="Отправлено" value={node.sent} /></div><section className="evidence-card"><div className="evidence-heading"><div className="evidence-icon"><ShieldAlert size={16} /></div><div><p className="eyebrow">ОБЪЯСНЯЕМОСТЬ</p><h3>Почему эта роль?</h3></div><CircleHelp size={15} className="muted-icon" /></div><p>{node.evidence}</p><div className="evidence-tags"><span>{node.incoming} входящих путей</span><span>{node.outgoing} исходящих путей</span></div></section><section className="cluster-card"><div className="cluster-card__heading"><span className="cluster-card__dot" style={{ backgroundColor: cluster.color }} /><div><p className="eyebrow">КОНТЕКСТ КЛАСТЕРА</p><h3>Кластер #{node.clusterId}</h3></div></div><div className="cluster-card__metrics"><span><b>{cluster.nNodes}</b> узлов</span><span><b>{cluster.nSeed}</b> seed</span><span><b>{cluster.internalTurnover}</b> внутри</span></div><p>{cluster.hypothesis}</p><div className="cluster-card__gids">Ключевые GID: {cluster.keyGids.join(' · ')}</div></section><div className="details-note">Оценки — аналитические гипотезы по наблюдаемой структуре сети. Перед действием проверьте подтверждающие операции.</div></aside>
}

function Metric({ icon, label, value }: { icon?: ReactNode; label: string; value: string }) { return <div className="metric"><div className="metric-label">{icon}{label}</div><strong>{value}</strong></div> }
