import {icon} from './icons.mjs';
import {events,nodes,colors,selectEvents} from './data.mjs';
import {copy} from './i18n.mjs';

const main=document.querySelector('#main'), dialog=document.querySelector('#details');
const state={language:'ru',page:'overview',filter:'all',query:'',reviewed:new Set(),selected:events[0].id};
// Session-only demo marks. No Telegram identity, token, or banking data is stored.
try{state.language=sessionStorage.getItem('fg-demo-language')||'ru';state.reviewed=new Set(JSON.parse(sessionStorage.getItem('fg-demo-reviews')||'[]').filter(id=>events.some(e=>e.id===id)));}catch{ /* Storage may be disabled in a WebView. */ }
if(!copy[state.language])state.language='ru';
const t=key=>copy[state.language][key]||key;
// Presence selects the Telegram presentation adapter, never authorizes access.
const tg=window.Telegram?.WebApp?.initData ? window.Telegram.WebApp : null;
const safeTelegram=fn=>{try{fn();}catch{ /* Browser preview and older Telegram clients remain usable. */ }};
function safeArea(){if(!tg)return;const top=(tg.safeAreaInset?.top||0)+(tg.contentSafeAreaInset?.top||0);const bottom=(tg.safeAreaInset?.bottom||0)+(tg.contentSafeAreaInset?.bottom||0);document.documentElement.style.setProperty('--safe-top',`${top}px`);document.documentElement.style.setProperty('--safe-bottom',`${bottom}px`);}
safeTelegram(()=>{tg?.ready();tg?.expand();tg?.setHeaderColor('#100d18');tg?.setBackgroundColor('#100d18');tg?.setBottomBarColor?.('#19121f');tg?.BackButton?.onClick(()=>{if(dialog.open)closeDetails();else navigate('overview');});tg?.onEvent('safeAreaChanged',safeArea);tg?.onEvent('contentSafeAreaChanged',safeArea);safeArea();});
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('suspended',document.hidden));
function haptic(){safeTelegram(()=>tg?.HapticFeedback?.selectionChanged());}
function storeDemo(){try{sessionStorage.setItem('fg-demo-reviews',JSON.stringify([...state.reviewed]));sessionStorage.setItem('fg-demo-language',state.language);}catch{}}
let toastTimer;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4500);}
function card(e){return `<button class="signal-card" data-detail="${e.id}" style="--risk:${colors[e.level]}" aria-label="${t('detail')} ${e.id}"><span class="priority-icon">${icon(e.level)}</span><span class="card-main"><span class="card-label">${state.reviewed.has(e.id)?icon('check'):''}${state.reviewed.has(e.id)?t('reviewed'):t('newConnection')}</span><span class="pair">${e.src}${icon('arrow')}${e.dst}</span><span class="card-meta">${t('cluster')} ${String(e.cluster).padStart(2,'0')} · ${e.time} · ${t(e.level)}</span></span><span class="card-score">${e.score}<span>/ 100</span></span>${icon('chevron','card-chevron')}</button>`;}
function curve(e){const a=nodes.find(n=>n.gid===e.src),b=nodes.find(n=>n.gid===e.dst),dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),ux=dx/d,uy=dy/d;return `M ${a.x+ux*(a.r+5)} ${a.y+uy*(a.r+5)} Q ${(a.x+b.x)/2-uy*16} ${(a.y+b.y)/2+ux*16} ${b.x-ux*(b.r+10)} ${b.y-uy*(b.r+10)}`;}
function graph(full=false){const selected=events.find(e=>e.id===state.selected);return `<section class="graph-card ${full?'full-graph':''}"><div class="graph-top"><h2>${t('network')}</h2><small>${t('networkHint')}</small></div><svg class="graph-svg" viewBox="0 0 560 400" role="group" aria-label="${t('network')}"><defs><pattern id="dots" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#624879" opacity=".25"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#a684c9"/></marker></defs><rect width="560" height="400" fill="url(#dots)"/><g class="graph-scene"><ellipse cx="280" cy="200" rx="205" ry="154" fill="none" stroke="#5c3b7933" stroke-dasharray="3 8"/>${events.map(e=>`<path class="edge ${e.id===state.selected?'active':''}" d="${curve(e)}" marker-end="url(#arrow)"/>${e.id===state.selected?`<path class="flow" d="${curve(e)}"/>`:''}`).join('')}${nodes.map(n=>`<g class="graph-node ${[selected.src,selected.dst].includes(n.gid)?'active':''}" transform="translate(${n.x} ${n.y})" data-gid="${n.gid}" role="button" tabindex="0" aria-label="GID ${n.gid}"><circle r="${n.r+7}" fill="#754d9f0d" stroke="#65438133"/><circle class="node-body" r="${n.r}"/><circle r="${n.r*.28}" fill="${colors[n.level]}"/><text class="node-label" y="${n.r+24}">${n.gid}</text></g>`).join('')}</g></svg>${full?`<div class="graph-toolbar"><button class="icon-button" data-zoom="out" aria-label="${t('zoomOut')}">${icon('minus')}</button><button class="icon-button" data-zoom="fit" aria-label="${t('fit')}">${icon('focus')}</button><button class="icon-button" data-zoom="in" aria-label="${t('zoomIn')}">${icon('plus')}</button></div>`:`<div class="graph-bottom"><span>${icon('graph')}6 ${t('nodes').toLowerCase()} · 5 ${t('directed').toLowerCase()}</span><button class="text-button" data-page="graph" aria-label="${t('openGraph')}">${icon('external')}</button></div>`}</section>`;}
function overview(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">${t('eyebrow')}</div><h1>${t('headline')}<span>${t('headlineAccent')}</span></h1><p>${t('intro')}</p><button class="primary" data-page="signals">${t('openSignals')}${icon('arrow')}</button></div><div class="hero-art" aria-hidden="true"><span class="orbit"></span><span class="orbit two"></span><img class="hero-mark" src="assets/mark.svg" alt=""><span class="satellite a">${icon('shield')}</span><span class="satellite b">${icon('graph')}</span><span class="satellite c"></span></div></section><section class="stats" aria-label="${t('synthetic')}"><div class="stat"><small>${icon('graph')}${t('newLinks')}</small><strong>05</strong></div><div class="stat"><small>${icon('critical')}${t('highPriority')}</small><strong>02</strong></div><div class="stat"><small>${icon('shield')}${t('inReview')}</small><strong>${String(state.reviewed.size).padStart(2,'0')}</strong></div></section><div class="overview-grid"><section><div class="section-head"><h2>${t('priorityQueue')}</h2><button class="text-button" data-page="signals">${t('viewAll')}${icon('chevron')}</button></div><div class="list">${events.slice(0,3).map(card).join('')}</div></section>${graph()}</div><section class="bot-banner">${icon('signals')}<div><h3>${t('botTitle')}</h3><p>${t('botText')}</p></div><button class="secondary" data-bot>${t('openBot')}${icon('external')}</button></section>`;}
function filteredList(){const list=selectEvents(state);return list.length?list.map(card).join(''):`<div class="empty">${icon('search')}<h2>${t('nothing')}</h2><p>${t('nothingHint')}</p><button class="secondary" data-clear>${t('clear')}</button></div>`;}
function signals(){return `<section class="signal-list-page"><div class="page-heading"><div class="eyebrow">${t('currentSnapshot')}</div><h1>${t('signals')}</h1><p>${t('signalsIntro')}</p></div><label class="search">${icon('search')}<span class="sr-only">${t('searchLabel')}</span><input id="search" type="search" placeholder="${t('search')}" autocomplete="off" maxlength="50"></label><div class="chips" role="group" aria-label="${t('signals')}">${[['all','all'],['high','highFilter'],['reviewed','reviewed']].map(([id,key])=>`<button class="chip" aria-pressed="${state.filter===id}" data-filter="${id}">${t(key)}${id==='reviewed'?` · ${state.reviewed.size}`:''}</button>`).join('')}</div><div class="list" id="signal-list" aria-live="polite">${filteredList()}</div></section>`;}
function network(){return `<div class="page-heading"><div class="eyebrow">${t('synthetic')}</div><h1>${t('graph')}</h1><p>${t('graphIntro')}</p></div>${graph(true)}<p class="graph-note">${t('legend')}</p><div class="legend" aria-label="${t('riskScale')}">${Object.entries(colors).map(([key,color])=>`<span style="--risk:${color}"><i></i>${t(key)}</span>`).join('')}</div><section class="selected-route"><h2>${t('selected')}</h2>${card(events.find(e=>e.id===state.selected))}</section>`;}
function render(){document.documentElement.lang=state.language;document.querySelector('#language').value=state.language;document.querySelector('#navigation').setAttribute('aria-label',t('overview'));document.querySelector('#navigation').innerHTML=['overview','signals','graph'].map(p=>`<button class="nav-item" data-page="${p}" ${state.page===p?'aria-current="page"':''}>${icon(p)}${t(p)}</button>`).join('');document.querySelector('#privacy').innerHTML=`${icon('lock')}<span>${t('privacy')}</span>`;main.innerHTML=state.page==='signals'?signals():state.page==='graph'?network():overview();const search=document.querySelector('#search');if(search)search.value=state.query;bindGraph();safeTelegram(()=>state.page==='overview'?tg?.BackButton?.hide():tg?.BackButton?.show());}
function navigate(page){if(!['overview','signals','graph'].includes(page))return;state.page=page;render();window.scrollTo({top:0,behavior:'instant'});}
let lastFocus;
function openDetails(id){const e=events.find(e=>e.id===id);if(!e)return;state.selected=id;lastFocus=document.activeElement;drawDetails(e);if(!dialog.open)dialog.showModal();safeTelegram(()=>tg?.BackButton?.show());}
function drawDetails(e){const marked=state.reviewed.has(e.id);dialog.innerHTML=`<div class="detail-content" style="--risk:${colors[e.level]}"><div class="dialog-head"><span class="eyebrow">${t('detail')} · ${e.id}</span><button class="icon-button" data-close aria-label="${t('close')}">${icon('close')}</button></div><div class="detail-identity"><span class="priority-icon">${icon(e.level)}</span><div><small>${t('newConnection')} · ${e.time}</small><h2 id="detail-title" class="pair">${e.src}${icon('arrow')}${e.dst}</h2></div></div><div class="detail-band"><span>${t('priority')}</span><strong>${e.score}<small>/ 100 · ${t(e.level)}</small></strong></div><section class="evidence"><h3>${icon('evidence')}${t('why')}</h3><p>${t(e.pattern)}</p><small>${t('evidenceHint')}</small></section><div class="detail-metrics"><div><small>${t('incoming')}</small><strong>${e.incoming}</strong></div><div><small>${t('outgoing')}</small><strong>${e.outgoing}</strong></div><div><small>${t('cluster')}</small><strong>0${e.cluster}</strong></div></div><p class="hypothesis">${icon('shield')}${t('hypothesis')}</p><div class="detail-actions"><button class="primary" data-review="${e.id}" aria-pressed="${marked}">${icon('check')}${marked?t('removeReview'):t('take')}</button><button class="secondary" data-show-graph="${e.id}">${icon('graph')}${t('openGraph')}</button></div><p class="detail-demo">${t('demoNotice')}</p></div>`;}
function closeDetails(){dialog.close();safeTelegram(()=>state.page==='overview'?tg?.BackButton?.hide():tg?.BackButton?.show());if(lastFocus?.isConnected)lastFocus.focus();else main.focus();}
dialog.addEventListener('cancel',event=>{event.preventDefault();closeDetails();});
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDetails();}});
document.querySelector('#language').addEventListener('change',event=>{state.language=event.target.value;storeDemo();render();if(dialog.open)drawDetails(events.find(e=>e.id===state.selected));});
document.addEventListener('input',event=>{if(event.target.id==='search'){state.query=event.target.value;document.querySelector('#signal-list').innerHTML=filteredList();}});
document.addEventListener('click',event=>{const target=event.target.closest('button,[data-gid]');if(!target)return;haptic();if(target.dataset.page)navigate(target.dataset.page);if(target.dataset.detail)openDetails(target.dataset.detail);if(target.dataset.gid){const e=events.find(e=>e.src===target.dataset.gid)||events.find(e=>e.dst===target.dataset.gid);if(e)openDetails(e.id);}if(target.hasAttribute('data-close'))closeDetails();if(target.dataset.filter){state.filter=target.dataset.filter;render();}if(target.hasAttribute('data-clear')){state.query='';state.filter='all';render();document.querySelector('#search')?.focus();}if(target.dataset.review){const id=target.dataset.review,was=state.reviewed.has(id);was?state.reviewed.delete(id):state.reviewed.add(id);storeDemo();render();drawDetails(events.find(e=>e.id===id));dialog.querySelector('[data-review]').focus();toast(t(was?'removedToast':'reviewToast'));}if(target.dataset.showGraph){state.selected=target.dataset.showGraph;closeDetails();navigate('graph');}if(target.hasAttribute('data-bot')){if(tg?.initData){safeTelegram(()=>tg.openTelegramLink('https://t.me/FreedomGraphbot'));}else window.open('https://t.me/FreedomGraphbot','_blank','noopener,noreferrer');}});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-gid]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.querySelector('.brand').addEventListener('click',event=>{event.preventDefault();navigate('overview');});
function bindGraph(){const svg=document.querySelector('.graph-svg'),scene=svg?.querySelector('.graph-scene');if(!svg)return;let scale=1,tx=0,ty=0,drag=null;const transform=()=>scene.setAttribute('transform',`translate(${280+tx} ${200+ty}) scale(${scale}) translate(-280 -200)`);document.querySelectorAll('[data-zoom]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.zoom==='fit'){scale=1;tx=0;ty=0;}else scale=Math.max(.7,Math.min(2.5,scale*(button.dataset.zoom==='in'?1.2:1/1.2)));transform();}));svg.addEventListener('pointerdown',event=>{if(event.target.closest('[data-gid]'))return;const matrix=svg.getScreenCTM()?.inverse();if(!matrix)return;const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix);drag={id:event.pointerId,x:point.x,y:point.y,tx,ty};svg.setPointerCapture(event.pointerId);});svg.addEventListener('pointermove',event=>{if(!drag||drag.id!==event.pointerId)return;const matrix=svg.getScreenCTM()?.inverse();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix);tx=Math.max(-400,Math.min(400,drag.tx+p.x-drag.x));ty=Math.max(-300,Math.min(300,drag.ty+p.y-drag.y));transform();});const end=()=>drag=null;svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);svg.addEventListener('lostpointercapture',end);}
render();
