import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, ArrowDownLeft, Banknote, Wallet, Search, SlidersHorizontal, Sparkles } from 'lucide-react'
import { DesignNetwork } from './components/DesignNetwork'
import { RiskAvatar } from './components/RiskAvatar'
import { mockEdges, mockNodes, roleMeta } from './data/mockData'
import { translations, roleOrder, riskColors, riskIndex, type Language } from './i18n'
import type { CSSProperties } from 'react'
import { brandMark, priorityArtwork } from './data/visualAssets'
import { getNodeArtwork, getClusterArtwork, roleArtwork, interfaceArtwork } from './data/networkArtwork'
import './design.css'
import './motion.css'

const metricIcons = [ArrowDownLeft, ArrowUpRight, Banknote, Wallet]

export default function DesignDashboard() {
  const [language,setLanguage]=useState<Language>(()=>{try{const saved=localStorage.getItem('freedom-language');return saved==='en'||saved==='kk'?saved:'ru'}catch{return 'ru'}})
  const t=translations[language]
  const [selectedId,setSelectedId]=useState(mockNodes[0].id)
  const [query,setQuery]=useState(''); const [searchError,setSearchError]=useState(false)
  const [role,setRole]=useState('all');const [cluster,setCluster]=useState('all');const [tierFilter,setTierFilter]=useState<number|null>(null)
  const [colorMode,setColorMode]=useState<'priority'|'role'|'cluster'>('priority');const [motion,setMotion]=useState(true)
  useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem('freedom-language',language)}catch{/* Storage is optional. */}},[language])
  const selected=mockNodes.find(n=>n.id===selectedId)??mockNodes[0];const tier=riskIndex(selected.priorityScore)
  const filtered=useMemo(()=>mockNodes.filter(n=>(role==='all'||n.role===role)&&(cluster==='all'||String(n.clusterId)===cluster)&&(tierFilter===null||riskIndex(n.priorityScore)===tierFilter)).sort((a,b)=>b.priorityScore-a.priorityScore),[role,cluster,tierFilter])
  const edges=useMemo(()=>{const ids=new Set(filtered.map(n=>n.id));return mockEdges.filter(e=>ids.has(e.source)&&ids.has(e.target))},[filtered])
  const roleLabel=(value:string)=>t.role[roleOrder.indexOf(value as typeof roleOrder[number])]
  const search=()=>{const found=mockNodes.find(n=>n.gid===query.trim());setSearchError(!found);if(found){setRole('all');setCluster('all');setTierFilter(null);setSelectedId(found.id)}}
  const evidenceIndex=[0,1,2,4,3,5][roleOrder.indexOf(selected.role)]
  return <div className={`freedom-shell ${motion?'':'motion-paused'}`}>
    <header className="freedom-header"><div className="freedom-brand"><span className="freedom-mark freedom-mark--artwork"><img src={brandMark} alt="" width="52" height="52" draggable={false}/></span><div><strong>Freedom<span>Graph</span></strong><small>{t.subtitle}</small></div></div><form className={`global-search ${searchError?'has-error':''}`} onSubmit={e=>{e.preventDefault();search()}}><Search size={17}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>{setQuery(e.target.value);setSearchError(false)}}/><button type="submit" aria-label={t.search}><ArrowUpRight size={16}/></button>{searchError&&<span role="status">{t.missing}</span>}</form><div className="demo-indicator"><i/>{t.demo}</div><nav className="language-switch" aria-label="Language">{(['ru','kk','en'] as const).map(l=><button key={l} lang={l} aria-pressed={language===l} onClick={()=>setLanguage(l)}>{l==='kk'?'KZ':l.toUpperCase()}</button>)}</nav><span className="bank-label">FREEDOM BANK</span></header>
    <div className="workspace-bar"><div><span className="section-number">01</span><h1>{t.network}</h1></div><div className="overview-stats"><span><b>{mockNodes.length}</b>{t.nodes}</span><span><b>{mockEdges.length}</b>{t.edges}</span><span><b>3</b>{t.clusters}</span></div><span className="period-label">{t.period}</span></div>
    <main className="freedom-workspace"><aside className="priority-panel"><div className="panel-title"><div><p className="micro-label">{t.priority}</p><h2>{t.top}</h2></div><span className="priority-heading-mark"><img src={interfaceArtwork.priority} alt="" width="28" height="28"/><span className="number-chip">{filtered.length.toString().padStart(2,'0')}</span></span></div><p className="panel-intro">{t.description}</p><div className="design-filters"><SlidersHorizontal size={14}/><select aria-label={t.roles} value={role} onChange={e=>setRole(e.target.value)}><option value="all">{t.all}</option>{roleOrder.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select><select aria-label={t.clusters} value={cluster} onChange={e=>setCluster(e.target.value)}><option value="all">{t.allClusters}</option>{[1,2,3].map(c=><option key={c} value={c}>#{c}</option>)}</select></div><div className="client-list">{filtered.map(n=><button key={n.id} className={`client-row ${n.id===selectedId?'selected':''}`} onClick={()=>setSelectedId(n.id)}><span className="client-rank">{String([...mockNodes].sort((a,b)=>b.priorityScore-a.priorityScore).findIndex(x=>x.id===n.id)+1).padStart(2,'0')}</span>{colorMode==='priority' ? <RiskAvatar score={n.priorityScore}/> : <img className="client-mode-artwork" src={getNodeArtwork(n,colorMode)} alt="" width="38" height="38" draggable={false}/>}<span className="client-info"><b>{n.gid}</b><small>{roleLabel(n.role)}</small></span><span className="client-score" style={{color:riskColors[riskIndex(n.priorityScore)]}}>{Math.round(n.priorityScore*100)}<small>/100</small></span></button>)}{!filtered.length&&<div className="design-empty">{t.empty}<button onClick={()=>{setRole('all');setCluster('all');setTierFilter(null)}}>{t.reset}</button></div>}</div><footer className="sidebar-foot"><img src={interfaceArtwork.caution} alt="" width="22" height="22"/><span>{t.note}</span></footer></aside>
    <section className="network-workspace"><DesignNetwork nodes={filtered} edges={edges} selectedId={selectedId} onSelect={setSelectedId} t={t} colorMode={colorMode} onColorMode={setColorMode} motion={motion} onMotion={()=>setMotion(v=>!v)}/><div className="priority-scale"><div className="scale-heading"><span>{t.levels}</span><small>{t.levelNote}</small></div><div className="scale-levels">{t.risk.map((label,i)=>{return <button aria-pressed={tierFilter===i} key={i} onClick={()=>setTierFilter(tierFilter===i?null:i)} style={{'--risk':riskColors[i]} as CSSProperties}><img className="tier-artwork" src={priorityArtwork[i]} alt="" width="38" height="38" draggable={false}/><span>{label}</span><b>{mockNodes.filter(n=>riskIndex(n.priorityScore)===i).length}</b><i/></button>})}</div></div></section>
    <aside className="client-details"><div className="panel-title"><div><p className="micro-label">{t.selected}</p><h2>{t.details}</h2></div><Sparkles size={17}/></div><section className="identity-card" style={{'--risk':riskColors[tier]} as CSSProperties}><RiskAvatar score={selected.priorityScore} large/><span className="identity-gid">GID {selected.gid}</span><span className="role-chip" style={{color:roleMeta[selected.role].color}}><img className="role-artwork" src={roleArtwork[selected.role]} alt="" width="24" height="24"/>{roleLabel(selected.role)}</span><div className="priority-tag"><i/>{t.risk[tier]}</div><div className="identity-scores"><div><small>{t.confidence}</small><strong>{Math.round(selected.roleScore*100)}<em>%</em></strong></div><div><small>{t.score}</small><strong style={{color:riskColors[tier]}}>{Math.round(selected.priorityScore*100)}<em>/100</em></strong></div></div></section><div className="detail-metrics">{[[t.incoming,selected.incoming],[t.outgoing,selected.outgoing],[t.received,selected.received],[t.sent,selected.sent]].map(([label,value],index)=>{const Icon=metricIcons[index];return <div key={label}><small className="metric-label"><Icon size={12} aria-hidden="true"/>{label}</small><b>{value}</b></div>})}</div><section className="why-card"><div><img className="evidence-artwork" src={interfaceArtwork.evidence} alt="" width="28" height="28"/><span className="micro-label">{t.evidence}</span></div><h3>{t.why}</h3><p>{t.explanations[evidenceIndex]}</p><span>{t.ruleNote}</span></section><div className="cluster-summary"><span className="micro-label">{t.context}</span><strong><span className="cluster-identity"><img src={getClusterArtwork(selected.clusterId)} alt="" width="32" height="32"/>{t.cluster} #{selected.clusterId}</span><span>{mockNodes.filter(n=>n.clusterId===selected.clusterId).length} {t.nodes.toLowerCase()}</span></strong><div>{mockNodes.filter(n=>n.clusterId===selected.clusterId).slice(0,3).map(n=><button key={n.id} onClick={()=>setSelectedId(n.id)}>{n.gid}<ArrowUpRight size={11}/></button>)}</div></div></aside></main><footer className="app-status"><span><i/>{t.snapshot} · FG-DEMO-01</span><span>{t.note}</span><span>FREEDOM GRAPH INTELLIGENCE</span></footer>
  </div>
}
