import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, ArrowDownLeft, Banknote, Wallet, Search, SlidersHorizontal, Sparkles } from 'lucide-react'
import { DesignNetwork } from './components/DesignNetwork'
import { RiskAvatar } from './components/RiskAvatar'
import { roleMeta } from './data/mockData'
import { translations, roleOrder, riskColors, riskIndex, type Language } from './i18n'
import type { CSSProperties } from 'react'
import { brandMark, priorityArtwork } from './data/visualAssets'
import { getNodeArtwork, getClusterArtwork, roleArtwork, interfaceArtwork } from './data/networkArtwork'
import './design.css'
import './motion.css'
import './integration.css'
import { useAnalysis, useNode } from './useAnalysis'
import { API, money } from './api'
import { AssistantChat } from './components/AssistantChat'

const metricIcons = [ArrowDownLeft, ArrowUpRight, Banknote, Wallet]

export default function DesignDashboard() {
  const [language,setLanguage]=useState<Language>(()=>{try{const saved=localStorage.getItem('freedom-language');return saved==='en'||saved==='kk'?saved:'ru'}catch{return 'ru'}})
  const t=translations[language]
  const { nodes, edges: allEdges, overview, clusters, loading, error, retry } = useAnalysis()
  const [selectedId,setSelectedId]=useState('')
  const [listLimit,setListLimit]=useState(100)
  const detail=useNode(selectedId, overview?.run_id)
  useEffect(()=>{if(nodes.length && !nodes.some(n=>n.id===selectedId))setSelectedId(nodes[0].id)},[nodes,selectedId])
  const [query,setQuery]=useState(''); const [searchError,setSearchError]=useState(false)
  const [role,setRole]=useState('all');const [cluster,setCluster]=useState('all');const [tierFilter,setTierFilter]=useState<number|null>(null)
  const [colorMode,setColorMode]=useState<'priority'|'role'|'cluster'>('priority');const [motion,setMotion]=useState(false)
  useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem('freedom-language',language)}catch{/* Storage is optional. */}},[language])
  const base=nodes.find(n=>n.id===selectedId)
  const selected=base && {...base, incoming:detail.card?.node.in_deg ?? 0, outgoing:detail.card?.node.out_deg ?? 0, received:detail.card?money(detail.card.node.in_kzt):'—', sent:detail.card?money(detail.card.node.out_kzt):'—', evidence:detail.card?.node.evidence ?? ''}
  const tier=riskIndex(selected?.priorityScore ?? 0)
  const filtered=useMemo(()=>nodes.filter(n=>(role==='all'||n.role===role)&&(cluster==='all'||String(n.clusterId)===cluster)&&(tierFilter===null||riskIndex(n.priorityScore)===tierFilter)).sort((a,b)=>b.priorityScore-a.priorityScore||a.id.localeCompare(b.id)),[nodes,role,cluster,tierFilter])
  const edges=useMemo(()=>{const ids=new Set(filtered.map(n=>n.id));return allEdges.filter(e=>ids.has(e.source)&&ids.has(e.target))},[filtered,allEdges])
  const roleLabel=(value:string)=>t.role[roleOrder.indexOf(value as typeof roleOrder[number])]
  const search=()=>{const found=nodes.find(n=>n.gid===query.trim());setSearchError(!found);if(found){setRole('all');setCluster('all');setTierFilter(null);setSelectedId(found.id)}}
  const choose=(gid:string)=>{setRole('all');setCluster('all');setTierFilter(null);setSelectedId(gid);window.location.hash='/node/'+gid}
  useEffect(()=>{const route=()=>{const parts=window.location.hash.slice(1).split('/');if(parts[1]==='node' && parts[2]){const found=nodes.find(n=>n.gid===parts[2]);if(found){setSelectedId(found.id);setRole('all');setCluster('all');setTierFilter(null)}else if(nodes.length){setQuery(parts[2]);setSearchError(true)}}else if(parts[1]==='cluster' && parts[2]){setCluster(parts[2]);setRole('all');setTierFilter(null)}};route();window.addEventListener('hashchange',route);return()=>window.removeEventListener('hashchange',route)},[nodes])
  const selectedCluster=clusters.find(c=>c.cluster_id===selected?.clusterId)
  if(loading||error||!selected)return <div className="integration-start"><h1>Freedom Graph</h1><p role="status">{loading?'Загружаем результат анализа…':error||'В результате нет узлов'}</p><button onClick={retry}>Повторить загрузку</button><a href="/check">Проверка API</a></div>

  return <div className={`freedom-shell ${motion?'':'motion-paused'}`}>
    <header className="freedom-header"><div className="freedom-brand"><span className="freedom-mark freedom-mark--artwork"><img src={brandMark} alt="" width="52" height="52" draggable={false}/></span><div><strong>Freedom<span>Graph</span></strong><small>{t.subtitle}</small></div></div><form className={`global-search ${searchError?'has-error':''}`} onSubmit={e=>{e.preventDefault();search()}}><Search size={17}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>{setQuery(e.target.value);setSearchError(false)}}/><button type="submit" aria-label={t.search}><ArrowUpRight size={16}/></button>{searchError&&<span role="status">{t.missing}</span>}</form><div className="demo-indicator"><i/>{overview?._synthetic?t.demo:'Данные анализа'}</div><nav className="language-switch" aria-label="Language">{(['ru','kk','en'] as const).map(l=><button key={l} lang={l} aria-pressed={language===l} onClick={()=>setLanguage(l)}>{l==='kk'?'KZ':l.toUpperCase()}</button>)}</nav><span className="bank-label">FREEDOM BANK</span></header>
    <div className="workspace-bar"><div><span className="section-number">01</span><h1>{t.network}</h1></div><div className="overview-stats"><span><b>{nodes.length}</b>{t.nodes}</span><span><b>{allEdges.length}</b>{t.edges}</span><span><b>{clusters.length}</b>{t.clusters}</span></div><span className="period-label">{overview?.period?.from} — {overview?.period?.to}</span></div>
    {overview?.last_attempt?.status==='failed'&&<div className="integration-warning">Последний пересчёт не удался. Показан предыдущий корректный результат.</div>}
    <div className="integration-toolbar"><span>Результаты — гипотезы для проверки, а не выводы о виновности.</span><button onClick={retry}>Обновить данные</button>{['nodes_roles.csv','clusters.csv','top_nodes.csv'].map(name=><a key={name} href={API+'/export/'+name}>↓ {name}</a>)}</div>
    <main className="freedom-workspace"><aside className="priority-panel"><div className="panel-title"><div><p className="micro-label">{t.priority}</p><h2>{t.top}</h2></div><span className="priority-heading-mark"><img src={interfaceArtwork.priority} alt="" width="28" height="28"/><span className="number-chip">{filtered.length.toString().padStart(2,'0')}</span></span></div><p className="panel-intro">{t.description}</p><div className="design-filters"><SlidersHorizontal size={14}/><select aria-label={t.roles} value={role} onChange={e=>setRole(e.target.value)}><option value="all">{t.all}</option>{roleOrder.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select><select aria-label={t.clusters} value={cluster} onChange={e=>setCluster(e.target.value)}><option value="all">{t.allClusters}</option>{clusters.map(item=>item.cluster_id).map(c=><option key={c} value={c}>#{c}</option>)}</select></div><div className="client-list">{filtered.slice(0,listLimit).map(n=><button key={n.id} className={`client-row ${n.id===selectedId?'selected':''}`} onClick={()=>choose(n.id)}><span className="client-rank">{String(nodes.findIndex(x=>x.id===n.id)+1).padStart(2,'0')}</span>{colorMode==='priority' ? <RiskAvatar score={n.priorityScore}/> : <img className="client-mode-artwork" src={getNodeArtwork(n,colorMode)} alt="" width="38" height="38" draggable={false}/>}<span className="client-info"><b>{n.gid}</b><small>{roleLabel(n.role)}</small></span><span className="client-score" style={{color:riskColors[riskIndex(n.priorityScore)]}}>{Math.round(n.priorityScore*100)}<small>/100</small></span></button>)}{filtered.length>listLimit&&<button className="load-more" onClick={()=>setListLimit(n=>n+100)}>Показать ещё 100</button>}{!filtered.length&&<div className="design-empty">{t.empty}<button onClick={()=>{setRole('all');setCluster('all');setTierFilter(null)}}>{t.reset}</button></div>}</div><footer className="sidebar-foot"><img src={interfaceArtwork.caution} alt="" width="22" height="22"/><span>{t.note}</span></footer></aside>
    <section className="network-workspace"><DesignNetwork limit={listLimit} nodes={filtered} edges={edges} selectedId={selectedId} onSelect={choose} t={t} colorMode={colorMode} onColorMode={setColorMode} motion={motion} onMotion={()=>setMotion(v=>!v)}/><div className="priority-scale"><div className="scale-heading"><span>{t.levels}</span><small>{t.levelNote}</small></div><div className="scale-levels">{t.risk.map((label,i)=>{return <button aria-pressed={tierFilter===i} key={i} onClick={()=>setTierFilter(tierFilter===i?null:i)} style={{'--risk':riskColors[i]} as CSSProperties}><img className="tier-artwork" src={priorityArtwork[i]} alt="" width="38" height="38" draggable={false}/><span>{label}</span><b>{nodes.filter(n=>riskIndex(n.priorityScore)===i).length}</b><i/></button>})}</div></div></section>
    <aside className="client-details"><div className="panel-title"><div><p className="micro-label">{t.selected}</p><h2>{t.details}</h2></div><Sparkles size={17}/></div><section className="identity-card" style={{'--risk':riskColors[tier]} as CSSProperties}><RiskAvatar score={selected.priorityScore} large/><span className="identity-gid">GID {selected.gid}</span><span className="role-chip" style={{color:roleMeta[selected.role].color}}><img className="role-artwork" src={roleArtwork[selected.role]} alt="" width="24" height="24"/>{roleLabel(selected.role)}</span><div className="priority-tag"><i/>{t.risk[tier]}</div><div className="identity-scores"><div><small>{t.confidence}</small><strong>{Math.round(selected.roleScore*100)}<em>%</em></strong></div><div><small>{t.score}</small><strong style={{color:riskColors[tier]}}>{Math.round(selected.priorityScore*100)}<em>/100</em></strong></div></div></section><div className="detail-metrics">{[[t.incoming,detail.card?selected.incoming:'—'],[t.outgoing,detail.card?selected.outgoing:'—'],[t.received,selected.received],[t.sent,selected.sent]].map(([label,value],index)=>{const Icon=metricIcons[index];return <div key={label}><small className="metric-label"><Icon size={12} aria-hidden="true"/>{label}</small><b>{value}</b></div>})}</div><section className="why-card"><div><img className="evidence-artwork" src={interfaceArtwork.evidence} alt="" width="28" height="28"/><span className="micro-label">{t.evidence}</span></div><h3>{t.why}</h3><p>{detail.error||selected.evidence||'Загружаем карточку…'}</p><span>{detail.card?.evidence_detail.rule_text || 'Правило из рассчитанного снимка'}</span></section><div className="node-flags">{base?.isSeed&&<span>Seed</span>}{base?.isBoundary&&<span>Граница обхода: исходящие не прослежены</span>}{base?.isIsolated&&<span>Изолированный узел</span>}</div><div className="cluster-summary"><span className="micro-label">{t.context}</span><strong><span className="cluster-identity"><img src={getClusterArtwork(selected.clusterId)} alt="" width="32" height="32"/>{t.cluster} #{selected.clusterId}</span><span>{selectedCluster?.n_nodes} {t.nodes.toLowerCase()}</span></strong><div>{nodes.filter(n=>selectedCluster?.top_gids.includes(n.gid)).slice(0,5).map(n=><button key={n.id} onClick={()=>choose(n.id)}>{n.gid}<ArrowUpRight size={11}/></button>)}</div><p className="cluster-hypothesis">{selectedCluster?.hypothesis}</p><p className="cluster-hypothesis">Seed: {selectedCluster?.n_seed} · Внутренний оборот: {selectedCluster?money(selectedCluster.sum_kzt_internal):'—'}</p><button className="load-more" onClick={()=>{setCluster(String(selected.clusterId));setRole('all');setTierFilter(null);window.location.hash='/cluster/'+selected.clusterId}}>Показать кластер</button></div></aside></main><footer className="app-status"><span><i/>Снимок · {overview?.run_id}</span><span>{t.note}</span><span>FREEDOM GRAPH INTELLIGENCE</span></footer>
    <AssistantChat runId={overview?.run_id||''} selectedGid={selectedId} onSelect={choose}/>
  </div>
}
