export type Language = 'ru' | 'kk' | 'en'
const copy = {
  ru: {
    subtitle: 'Финансовая сетевая аналитика', search: 'Поиск по GID', missing: 'GID не найден', nodes: 'Узлы', edges: 'Связи', clusters: 'Кластеры', demo: 'Демонстрационные данные', priority: 'Приоритет проверки', top: 'Клиенты в фокусе', description: 'Начните с наиболее значимых сигналов.', all: 'Все роли', allClusters: 'Все кластеры', empty: 'По этим фильтрам ничего не найдено', network: 'Карта финансовых связей', networkSub: 'ОБЗОР СЕТИ', roles: 'Роли', signals: 'Приоритет', fit: 'Весь граф', zoomIn: 'Приблизить', zoomOut: 'Отдалить', pause: 'Приостановить анимацию', play: 'Включить анимацию', map: 'Казахстан', direction: 'Плательщик → получатель', details: 'Карточка клиента', selected: 'ВЫБРАННЫЙ УЗЕЛ', confidence: 'Соответствие роли', score: 'Приоритет проверки', incoming: 'Входящие связи', outgoing: 'Исходящие связи', received: 'Получено', sent: 'Отправлено', why: 'Почему эта роль?', evidence: 'ОБОСНОВАНИЕ', cluster: 'Кластер', context: 'КОНТЕКСТ СЕТИ', note: 'Оценки — аналитические гипотезы, а не вероятность нарушения.', levels: 'Шкала приоритета', levelNote: 'Цвет показывает очередность проверки', reset: 'Сбросить фильтры', snapshot: 'ДЕМО-СНИМОК', period: '1–31 июля 2026', selection: 'Выберите узел для анализа', ruleNote: 'Показатели и объяснения в этом макете синтетические.',
    risk: ['Критический', 'Высокий', 'Средний', 'Низкий', 'Минимальный'],
    role: ['Консолидатор', 'Транзит', 'Распределитель', 'Конечный получатель', 'Координатор', 'Периферийный'],
    explanations: ['Получает средства от 14 клиентов и направляет основной объём двум получателям.', 'Входящий и исходящий наблюдаемые потоки сопоставимы.', 'Распределяет входящий поток между несколькими получателями.', 'Связывает плотные группы и несколько путей переводов.', 'В наблюдаемом фрагменте есть входящие потоки без исходящих.', 'Небольшое число связей; данных для специализированной роли недостаточно.'],
  },
  kk: {
    subtitle: 'Қаржылық желіні талдау', search: 'GID бойынша іздеу', missing: 'GID табылмады', nodes: 'Түйіндер', edges: 'Байланыстар', clusters: 'Кластерлер', demo: 'Демонстрациялық деректер', priority: 'Тексеру басымдығы', top: 'Назардағы клиенттер', description: 'Ең маңызды белгілерден бастаңыз.', all: 'Барлық рөлдер', allClusters: 'Барлық кластерлер', empty: 'Бұл сүзгілер бойынша түйіндер табылмады', network: 'Қаржылық байланыстар картасы', networkSub: 'ЖЕЛІГЕ ШОЛУ', roles: 'Рөлдер', signals: 'Басымдық', fit: 'Толық граф', zoomIn: 'Жақындату', zoomOut: 'Алыстату', pause: 'Анимацияны тоқтату', play: 'Анимацияны қосу', map: 'Қазақстан', direction: 'Төлеуші → алушы', details: 'Клиент карточкасы', selected: 'ТАҢДАЛҒАН ТҮЙІН', confidence: 'Рөлге сәйкестік', score: 'Тексеру басымдығы', incoming: 'Кіріс байланыстар', outgoing: 'Шығыс байланыстар', received: 'Алынған сома', sent: 'Жіберілген сома', why: 'Неліктен осы рөл?', evidence: 'НЕГІЗДЕМЕ', cluster: 'Кластер', context: 'ЖЕЛІ КОНТЕКСТІ', note: 'Бағалар — талдау болжамдары, құқық бұзушылық ықтималдығы емес.', levels: 'Басымдық шкаласы', levelNote: 'Түс тексеру кезектілігін көрсетеді', reset: 'Сүзгілерді тазарту', snapshot: 'ДЕМО-КӨРІНІС', period: '2026 жылғы 1–31 шілде', selection: 'Талдау үшін түйінді таңдаңыз', ruleNote: 'Бұл макеттегі көрсеткіштер мен түсіндірмелер жасанды.',
    risk: ['Критикалық', 'Жоғары', 'Орташа', 'Төмен', 'Минималды'],
    role: ['Шоғырландырушы', 'Транзит', 'Таратушы', 'Соңғы алушы', 'Үйлестіруші', 'Шеткі'],
    explanations: ['14 клиенттен қаражат алып, негізгі көлемді екі алушыға жібереді.', 'Бақыланатын кіріс және шығыс ағындары шамалас.', 'Кіріс ағынын бірнеше алушы арасында таратады.', 'Тығыз топтар мен бірнеше аударым жолдарын байланыстырады.', 'Бақыланатын бөлікте кіріс ағындары бар, шығыс ағындары жоқ.', 'Байланыстар аз; арнайы рөлді анықтауға деректер жеткіліксіз.'],
  },
  en: {
    subtitle: 'Financial network intelligence', search: 'Search by GID', missing: 'GID not found', nodes: 'Nodes', edges: 'Connections', clusters: 'Clusters', demo: 'Demonstration data', priority: 'Review priority', top: 'Clients in focus', description: 'Start with the most significant signals.', all: 'All roles', allClusters: 'All clusters', empty: 'No nodes match these filters', network: 'Financial connections map', networkSub: 'NETWORK OVERVIEW', roles: 'Roles', signals: 'Priority', fit: 'Fit graph', zoomIn: 'Zoom in', zoomOut: 'Zoom out', pause: 'Pause animation', play: 'Play animation', map: 'Kazakhstan', direction: 'Payer → receiver', details: 'Client details', selected: 'SELECTED NODE', confidence: 'Role confidence', score: 'Review priority', incoming: 'Incoming links', outgoing: 'Outgoing links', received: 'Received', sent: 'Sent', why: 'Why this role?', evidence: 'EVIDENCE', cluster: 'Cluster', context: 'NETWORK CONTEXT', note: 'Scores are analytical hypotheses, not probabilities of misconduct.', levels: 'Priority scale', levelNote: 'Color indicates the order of review', reset: 'Reset filters', snapshot: 'DEMO SNAPSHOT', period: '1–31 July 2026', selection: 'Select a node to investigate', ruleNote: 'Metrics and explanations in this preview are synthetic.',
    risk: ['Critical', 'High', 'Medium', 'Low', 'Minimal'],
    role: ['Consolidator', 'Transit', 'Distributor', 'Terminal', 'Coordinator', 'Peripheral'],
    explanations: ['Receives funds from 14 clients and sends most of the volume to two recipients.', 'Observed incoming and outgoing volumes are comparable.', 'Distributes the incoming flow among multiple recipients.', 'Connects dense groups and several transfer paths.', 'The observed fragment has incoming flows with no outgoing transfers.', 'Few connections; insufficient evidence for a specialized role.'],
  },
}
export const translations = copy
export type Copy = typeof copy.ru
export const roleOrder = ['consolidator', 'transit', 'distributor', 'terminal', 'coordinator', 'peripheral'] as const
export const riskColors = ['#ff6b74', '#f7a34b', '#e5cf64', '#47c79b', '#60c9df']
// Visual tiers for the synthetic preview only; these do not alter analytical scores.
export const riskIndex = (score: number) => score >= .9 ? 0 : score >= .75 ? 1 : score >= .6 ? 2 : score >= .5 ? 3 : 4
