/* Framework-independent website component. API key never enters the browser. */
class MoneyGraphAssistant extends HTMLElement {
  constructor(){super();this.attachShadow({mode:'open'});this.history=[];this.busy=false;this.runId=null;}
  connectedCallback(){if(this.started)return;this.started=true;this.render();this.refresh();}
  get base(){return (this.getAttribute('api-base')||'/api/v1').replace(/\/$/,'');}
  render(){this.shadowRoot.innerHTML=`<style>
  :host{display:block;color:#19333e;font:14px system-ui,sans-serif}*{box-sizing:border-box}.box{border:1px solid #dce5e9;border-radius:14px;background:white;overflow:hidden}.header{padding:18px 20px;border-bottom:1px solid #e1e9ec;display:flex;gap:15px;justify-content:space-between;align-items:center}h2{font-size:18px;margin:0 0 5px}.status{font-size:12px;color:#597581}.messages{height:380px;overflow:auto;padding:18px;display:flex;flex-direction:column;gap:12px}.msg{max-width:95%;padding:12px 14px;border-radius:10px;background:#f0f5f7;white-space:pre-wrap;line-height:1.6;overflow-wrap:anywhere}.user{background:#e0f2eb;align-self:flex-end}.error{background:#fff1e8;color:#8b4d25}.label{display:block;font-size:11px;color:#5d7580;margin-bottom:5px}a{color:#087567;font-weight:600}details{font-size:12px;margin-top:10px}pre{white-space:pre-wrap;max-height:150px;overflow:auto;font-size:11px}form{padding:18px;border-top:1px solid #e1e9ec}textarea{width:100%;min-height:90px;resize:vertical;border:1px solid #b7cbd1;border-radius:8px;padding:10px;font:inherit}.actions{display:flex;justify-content:space-between;gap:10px;margin-top:10px}button{font:inherit;border-radius:7px;border:1px solid #c5d7db;background:white;color:#244853;padding:8px 12px;cursor:pointer}button.primary{background:#117c6d;color:white;border-color:#117c6d}button:disabled{opacity:.5;cursor:default}.suggestions{padding:0 18px 15px;display:flex;gap:7px;flex-wrap:wrap}.suggestions button{text-align:left;font-size:12px}.note{font-size:11px;color:#5c7380;margin:9px 0 0;line-height:1.5}
  </style><section class="box"><div class="header"><div><h2>AI-ассистент по графу</h2><div class="status" role="status">Проверяю подключение…</div></div><button class="refresh" type="button">Обновить</button></div><div class="messages" role="log" aria-live="polite"></div><div class="suggestions"></div><form><label for="question">Вопрос по данным</label><textarea id="question" maxlength="4000" placeholder="Например: кто собирает деньги с этих участников?" required></textarea><div class="actions"><button class="clear" type="button">Очистить диалог</button><button class="primary send" type="submit" disabled>Отправить</button></div><p class="note">Ответ строится по текущему снимку. Внешней модели передаются вопрос и ограниченные результаты инструментов. История хранится только до закрытия страницы.</p></form></section>`;
  const q=s=>this.shadowRoot.querySelector(s);this.messages=q('.messages');this.input=q('textarea');this.send=q('.send');this.status=q('.status');q('form').onsubmit=e=>{e.preventDefault();this.ask();};q('.refresh').onclick=()=>this.refresh();q('.clear').onclick=()=>{if(!this.busy){this.history=[];this.messages.replaceChildren();}};this.addMessage('assistant','Могу объяснить роль узла, найти общих получателей, показать пути и помочь выбрать приоритет проверки.');}
  setQuestion(question){this.input.value=question;this.input.focus();}
  addMessage(role,text,{gids=[],calls=null,error=false}={}){const block=document.createElement('div');block.className='msg '+(error?'error':role);const label=document.createElement('span');label.className='label';label.textContent=role==='user'?'Вы':error?'Сообщение сервиса':'Ассистент';block.append(label);const allowed=new Set(gids);let last=0;for(const m of text.matchAll(/#([0-9]{1,19})(?![0-9])/g)){block.append(document.createTextNode(text.slice(last,m.index)));if(allowed.has(m[1])){const a=document.createElement('a');a.textContent=m[0];a.href='/#/node/'+m[1];a.onclick=e=>{const event=new CustomEvent('graph-node-select',{detail:{gid:m[1]},bubbles:true,composed:true,cancelable:true});if(!this.dispatchEvent(event))e.preventDefault();};block.append(a);}else block.append(document.createTextNode(m[0]));last=m.index+m[0].length;}block.append(document.createTextNode(text.slice(last)));if(calls?.length){const d=document.createElement('details'),s=document.createElement('summary'),p=document.createElement('pre');s.textContent='Какие данные использованы';p.textContent=calls.map(x=>x.name+' '+JSON.stringify(x.args)+' · '+(x.ok===false?'ошибка':'OK')+' · '+(x.ms??'?')+' мс').join('\n');d.append(s,p);block.append(d);}this.messages.append(block);this.messages.scrollTop=this.messages.scrollHeight;return block;}
  async refresh(){try{const r=await fetch(this.base+'/assistant/status');if(!r.ok)throw Error();const d=await r.json();if(this.runId&&d.run_id!==this.runId){this.history=[];this.messages.replaceChildren();this.addMessage('assistant','Снимок изменился. История очищена, чтобы не смешивать результаты.');}this.runId=d.run_id;this.ready=d.ready;this.status.textContent=!d.run_id?'Нет результата анализа':!d.enabled?'Локальный режим · без OpenAI':'Готов · снимок '+d.run_id;this.send.disabled=!this.ready||this.busy;const sr=await fetch(this.base+'/assistant/suggestions');if(sr.ok){const suggestions=await sr.json(),box=this.shadowRoot.querySelector('.suggestions');box.replaceChildren();for(const text of suggestions.items){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>this.setQuestion(text);box.append(b);}}return true;}catch{this.ready=false;this.send.disabled=true;this.status.textContent='Сервис недоступен. Проверьте запуск backend.';return false;}}
  async ask(){if(this.busy)return;const question=this.input.value.trim();if(!question)return;this.busy=true;this.send.disabled=true;await this.refresh();if(!this.ready){this.busy=false;return;}this.input.value='';this.addMessage('user',question);const waiting=this.addMessage('assistant','Проверяю данные графа…');const control=new AbortController(),timer=setTimeout(()=>control.abort(),65000);try{const r=await fetch(this.base+'/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:this.history.slice(-6)}),signal:control.signal});const d=await r.json();waiting.remove();if(!r.ok)throw Error(d.error?.message||'Не удалось получить ответ');const answeredRun=r.headers.get('X-Analysis-Run-Id');if(answeredRun&&this.runId!==answeredRun){this.history=[];this.runId=answeredRun;this.addMessage('assistant','Ответ относится к обновлённому снимку '+answeredRun+'.');}this.addMessage('assistant',(d.mode==='fallback'?'Локальный разбор (fallback)\n\n':'')+d.answer+(d.warnings?.length?'\n\nПримечания: '+d.warnings.join('; '):''),{gids:d.gids,calls:d.tool_calls});this.history.push({role:'user',content:question},{role:'assistant',content:d.answer});this.history=this.history.slice(-6);}catch(e){waiting.remove();this.input.value=question;this.addMessage('assistant',e.name==='AbortError'?'Истекло время ожидания. Попробуйте более конкретный вопрос.':e.message,{error:true});}finally{clearTimeout(timer);this.busy=false;this.send.disabled=!this.ready;}}
}
if(!customElements.get('moneygraph-assistant'))customElements.define('moneygraph-assistant',MoneyGraphAssistant);
